"""Tests for the shared fuzzing input strategies."""

import random

from ..strategies import fuzzed_bytecode, fuzzed_calldata

TERMINATORS = {0x00, 0xF3, 0xFD}  # STOP, RETURN, REVERT


def test_bytecode_is_deterministic() -> None:
    """The same seed yields identical bytecode."""
    assert bytes(fuzzed_bytecode(random.Random(1))) == bytes(
        fuzzed_bytecode(random.Random(1))
    )


def test_distinct_seeds_differ() -> None:
    """Different seeds (very likely) yield different bytecode."""
    a = bytes(fuzzed_bytecode(random.Random(1)))
    b = bytes(fuzzed_bytecode(random.Random(2)))
    assert a != b


def test_bytecode_ends_in_terminator() -> None:
    """Generated bytecode ends in STOP, RETURN, or REVERT."""
    for seed in range(20):
        code = bytes(fuzzed_bytecode(random.Random(seed)))
        assert code[-1] in TERMINATORS


def test_bytecode_is_nonempty() -> None:
    """Generated bytecode always contains at least the anchor + terminator."""
    for seed in range(20):
        assert len(bytes(fuzzed_bytecode(random.Random(seed)))) >= 2


def test_calldata_respects_max_size() -> None:
    """Calldata never exceeds the requested maximum size."""
    for seed in range(50):
        data = fuzzed_calldata(random.Random(seed), max_size=32)
        assert 0 <= len(data) <= 32


def test_calldata_is_deterministic() -> None:
    """The same seed yields identical calldata."""
    assert fuzzed_calldata(random.Random(7)) == fuzzed_calldata(
        random.Random(7)
    )
