"""Tests for the shared fuzzing input strategies."""

import random

from ..strategies import fuzzed_bytecode, fuzzed_calldata

TERMINATORS = {0x00, 0xF3, 0xFD}  # STOP, RETURN, REVERT
STATICCALL = 0xFA
PRECOMPILES = list(range(1, 12))


def test_bytecode_is_deterministic() -> None:
    """The same seed yields identical bytecode."""
    assert bytes(fuzzed_bytecode(random.Random(1))) == bytes(
        fuzzed_bytecode(random.Random(1))
    )


def test_distinct_seeds_differ() -> None:
    """Different seeds (very likely) yield different bytecode."""
    a = bytes(fuzzed_bytecode(random.Random(1)))
    b = bytes(fuzzed_bytecode(random.Random(2)))
    assert a != b


def test_bytecode_ends_in_terminator() -> None:
    """Generated bytecode ends in STOP, RETURN, or REVERT."""
    for seed in range(20):
        code = bytes(fuzzed_bytecode(random.Random(seed)))
        assert code[-1] in TERMINATORS


def test_bytecode_is_nonempty() -> None:
    """Generated bytecode always contains at least the anchor + terminator."""
    for seed in range(20):
        assert len(bytes(fuzzed_bytecode(random.Random(seed)))) >= 2


def test_calldata_respects_max_size() -> None:
    """Calldata never exceeds the requested maximum size."""
    for seed in range(50):
        data = fuzzed_calldata(random.Random(seed), max_size=32)
        assert 0 <= len(data) <= 32


def test_calldata_is_deterministic() -> None:
    """The same seed yields identical calldata."""
    assert fuzzed_calldata(random.Random(7)) == fuzzed_calldata(
        random.Random(7)
    )


def _push20_operands(code: bytes) -> list[bytes]:
    """
    Return the 20-byte operands of every PUSH20, walking the code so that
    bytes inside push immediates are not mistaken for opcodes (a raw byte
    scan is unreliable — random PUSH32 data contains arbitrary bytes).
    """
    operands = []
    i = 0
    while i < len(code):
        op = code[i]
        if 0x60 <= op <= 0x7F:  # PUSH1..PUSH32
            width = op - 0x5F
            if op == 0x73:  # PUSH20
                operands.append(code[i + 1 : i + 1 + width])
            i += 1 + width
        else:
            i += 1
    return operands


def _has_opcode(code: bytes, opcode: int) -> bool:
    """True if ``opcode`` appears as an instruction (not push data)."""
    i = 0
    while i < len(code):
        op = code[i]
        if op == opcode:
            return True
        i += 1 + (op - 0x5F) if 0x60 <= op <= 0x7F else 1
    return False


def test_no_precompile_calls_without_addresses() -> None:
    """Without supplied precompiles, no STATICCALL is emitted."""
    for seed in range(20):
        code = bytes(fuzzed_bytecode(random.Random(seed)))
        assert not _has_opcode(code, STATICCALL)


def test_precompile_calls_injected_when_supplied() -> None:
    """Supplying precompiles guarantees at least one call into one per body."""
    for seed in range(20):
        code = bytes(
            fuzzed_bytecode(random.Random(seed), precompiles=PRECOMPILES)
        )
        assert any(_has_opcode(code, op) for op in (0xF1, 0xF2, STATICCALL))


def test_precompile_call_targets_supplied_address() -> None:
    """An injected call targets a supplied precompile (or the boundary)."""
    allowed = {a.to_bytes(20, "big") for a in PRECOMPILES}
    allowed.add((max(PRECOMPILES) + 1).to_bytes(20, "big"))
    for seed in range(20):
        code = bytes(
            fuzzed_bytecode(random.Random(seed), precompiles=PRECOMPILES)
        )
        assert any(operand in allowed for operand in _push20_operands(code))


def test_precompile_bytecode_is_deterministic() -> None:
    """The same seed and precompile set yield identical bytecode."""
    a = bytes(fuzzed_bytecode(random.Random(3), precompiles=PRECOMPILES))
    b = bytes(fuzzed_bytecode(random.Random(3), precompiles=PRECOMPILES))
    assert a == b


CALL, CALLCODE, DELEGATECALL = 0xF1, 0xF2, 0xF4
CALL_FAMILY = (CALL, CALLCODE, DELEGATECALL, STATICCALL)
TARGETS = [0x10000, 0x10001]


def test_call_family_injected_when_targets_supplied() -> None:
    """Supplying call targets yields every kind of message call."""
    seen = set()
    for seed in range(40):
        code = bytes(
            fuzzed_bytecode(random.Random(seed), call_targets=TARGETS)
        )
        seen |= {op for op in CALL_FAMILY if _has_opcode(code, op)}
    assert seen == set(CALL_FAMILY)


def test_no_message_calls_without_targets_or_precompiles() -> None:
    """A bare body never calls out."""
    for seed in range(20):
        code = bytes(fuzzed_bytecode(random.Random(seed)))
        assert not any(_has_opcode(code, op) for op in CALL_FAMILY)


def test_precompile_calls_include_value_bearing_variants() -> None:
    """Precompiles are reached with value-bearing CALL and CALLCODE too."""
    seen = set()
    for seed in range(60):
        code = bytes(
            fuzzed_bytecode(random.Random(seed), precompiles=PRECOMPILES)
        )
        seen |= {
            op for op in (CALL, CALLCODE, STATICCALL) if _has_opcode(code, op)
        }
    assert seen == {CALL, CALLCODE, STATICCALL}


def test_call_targets_appear_as_push20_operands() -> None:
    """Every supplied target is called somewhere across seeds."""
    found = set()
    for seed in range(40):
        code = bytes(
            fuzzed_bytecode(random.Random(seed), call_targets=TARGETS)
        )
        found |= {int.from_bytes(o, "big") for o in _push20_operands(code)}
    assert set(TARGETS) <= found


def test_call_family_bytecode_is_deterministic() -> None:
    """Injected calls are fully determined by the rng."""
    a = bytes(fuzzed_bytecode(random.Random(5), call_targets=TARGETS))
    b = bytes(fuzzed_bytecode(random.Random(5), call_targets=TARGETS))
    assert a == b


CREATE, CREATE2, SELFDESTRUCT, TSTORE, LOG1 = 0xF0, 0xF5, 0xFF, 0x5D, 0xA1
GAS, SELFBALANCE, RETURNDATASIZE, SSTORE, STOP = 0x5A, 0x47, 0x3D, 0x55, 0x00


def _instructions(code: bytes) -> list[int]:
    ops, i = [], 0
    while i < len(code):
        op = code[i]
        ops.append(op)
        i += 1 + (op - 0x5F) if 0x60 <= op <= 0x7F else 1
    return ops


def test_epilogue_witnesses_gas_returndata_and_balance() -> None:
    """Every body ends by storing GAS, RETURNDATASIZE and SELFBALANCE."""
    for seed in range(10):
        ops = _instructions(bytes(fuzzed_bytecode(random.Random(seed))))
        tail = ops[-12:]
        assert GAS in tail and RETURNDATASIZE in tail and SELFBALANCE in tail
        assert tail.count(SSTORE) >= 3


def test_shapes_emit_creation_and_selfdestruct_calls() -> None:
    """
    With targets and a destructor, CREATE2 recursion and a callcode into
    a selfdestructing helper both appear across seeds.
    """
    seen: set[int] = set()
    destructor_called = False
    for seed in range(60):
        code = bytes(
            fuzzed_bytecode(
                random.Random(seed),
                call_targets=[0x10000],
                selfdestructor=0x10010,
            )
        )
        seen |= set(_instructions(code)) & {CREATE2, 0xF2}
        operands = {int.from_bytes(o, "big") for o in _push20_operands(code)}
        destructor_called |= 0x10010 in operands
    assert CREATE2 in seen and 0xF2 in seen and destructor_called


def test_palette_reaches_new_opcode_families() -> None:
    """Creation, transient storage, logs and EXTCODE* are in the walk."""
    seen = set()
    for seed in range(80):
        seen |= set(_instructions(bytes(fuzzed_bytecode(random.Random(seed)))))
    assert {CREATE, TSTORE, LOG1, 0x3B} <= seen  # 0x3B EXTCODESIZE


def test_no_shapes_without_targets() -> None:
    """A bare body still carries no message calls and no CREATE2 template."""
    for seed in range(20):
        ops = _instructions(bytes(fuzzed_bytecode(random.Random(seed))))
        assert not any(op in ops for op in (0xF1, 0xF2, 0xF4, 0xFA))
