"""
Seeded, reproducible generator of ``FuzzerOutput`` cases.

Every case is fully determined by ``(fork, GENERATOR_VERSION, seed)``, so a
seed alone reproduces a case exactly. Bump ``GENERATOR_VERSION`` whenever the
generation logic changes, so old seeds are never silently reinterpreted.

The bytecode generator is *stack-aware*: it tracks a virtual stack height and
only emits an opcode once enough items are present (pushing operands first
when needed). This keeps generated programs executing real logic instead of
reverting immediately on a stack underflow, which is what makes the corpus
worth running.
"""

import random
from typing import Dict, List

from execution_testing.base_types import (
    Address,
    Bytes,
    Hash,
    HexNumber,
)
from execution_testing.forks import Fork
from execution_testing.test_types import Environment
from execution_testing.test_types.account_types import EOA
from execution_testing.vm import Bytecode
from execution_testing.vm import Opcodes as Op

from .models import (
    FuzzerAccountInput,
    FuzzerOutput,
    FuzzerTransactionInput,
)

GENERATOR_VERSION = 1

# Opcode palette for generated contract bodies, grouped so the generator can
# bias toward operations that keep execution interesting. Dynamic jumps are
# deliberately excluded: without a control-flow model they almost always hit
# an invalid jump destination and abort, which defeats the purpose.
_ARITHMETIC = [
    Op.ADD,
    Op.MUL,
    Op.SUB,
    Op.DIV,
    Op.MOD,
    Op.EXP,
    Op.LT,
    Op.GT,
    Op.EQ,
    Op.ISZERO,
    Op.AND,
    Op.OR,
    Op.XOR,
    Op.NOT,
    Op.SHL,
    Op.SHR,
    Op.SAR,
    Op.BYTE,
    Op.SIGNEXTEND,
]
_MEMORY = [Op.MSTORE, Op.MSTORE8, Op.MLOAD, Op.MSIZE]
_STORAGE = [Op.SSTORE, Op.SLOAD]
_ENV = [
    Op.ADDRESS,
    Op.CALLER,
    Op.CALLVALUE,
    Op.ORIGIN,
    Op.GASPRICE,
    Op.NUMBER,
    Op.TIMESTAMP,
    Op.GASLIMIT,
    Op.CHAINID,
    Op.SELFBALANCE,
    Op.CALLDATASIZE,
    Op.CODESIZE,
    Op.GAS,
    Op.BASEFEE,
]
_KECCAK = [Op.SHA3]
_STACK_SHUFFLE = [Op.DUP1, Op.DUP2, Op.SWAP1, Op.SWAP2, Op.POP]

_PALETTE = (
    _ARITHMETIC * 3
    + _MEMORY * 2
    + _STORAGE * 2
    + _ENV * 2
    + _KECCAK
    + _STACK_SHUFFLE * 2
)


def _derive_key(rng: random.Random) -> Hash:
    """Draw a valid secp256k1 private key deterministically."""
    # secp256k1 order; any value in [1, n-1] is a valid key.
    n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
    return Hash((rng.randrange(1, n)).to_bytes(32, "big"))


def _generate_bytecode(rng: random.Random, max_ops: int) -> Bytes:
    """
    Build a stack-safe contract body ending in a clean terminator.

    The generator maintains a running stack-height estimate and pushes
    32-byte operands whenever the chosen opcode needs more items than are
    available, so most instructions run rather than underflow.
    """
    code: Bytecode = Bytecode() + Op.JUMPDEST  # harmless leading anchor
    stack_height = 0
    num_ops = rng.randint(1, max_ops)

    for _ in range(num_ops):
        op = rng.choice(_PALETTE)
        needed = op.min_stack_height
        while stack_height < needed:
            operand = rng.getrandbits(256)
            code += Op.PUSH32(operand)
            stack_height += 1
        code += op
        stack_height += op.pushed_stack_items - op.popped_stack_items
        # Guard against unbounded growth confusing later opcodes.
        if stack_height > 900:
            code += Op.POP
            stack_height -= 1

    terminator = rng.choice([Op.STOP, Op.RETURN, Op.REVERT])
    if terminator in (Op.RETURN, Op.REVERT):
        while stack_height < 2:
            code += Op.PUSH1(0)
            stack_height += 1
        code += terminator
    else:
        code += Op.STOP

    return Bytes(bytes(code))


def generate_fuzzer_output(
    fork: Fork,
    seed: int,
    *,
    num_senders: int = 3,
    num_contracts: int = 3,
    num_transactions: int = 5,
    max_ops_per_contract: int = 40,
) -> FuzzerOutput:
    """
    Generate one reproducible ``FuzzerOutput`` for the given fork and seed.

    Senders are funded EOAs with deterministic keys; contracts hold
    stack-aware generated bytecode. Transactions reference senders and
    target contracts (or perform value transfers) with correct per-sender
    nonces.
    """
    # Seed from a stable string; a raw tuple hash would be salted per process.
    rng = random.Random(f"{GENERATOR_VERSION}:{fork.name()}:{seed}")

    accounts: Dict[Address, FuzzerAccountInput] = {}

    sender_addresses: List[Address] = []
    for _ in range(num_senders):
        key = _derive_key(rng)
        address = Address(EOA(key=key))
        accounts[address] = FuzzerAccountInput(
            balance=HexNumber(10**20),
            nonce=HexNumber(0),
            private_key=key,
        )
        sender_addresses.append(address)

    contract_addresses: List[Address] = []
    for i in range(num_contracts):
        address = Address(0x10000 + i)
        accounts[address] = FuzzerAccountInput(
            balance=HexNumber(rng.randrange(0, 10**18)),
            nonce=HexNumber(0),
            code=_generate_bytecode(rng, max_ops_per_contract),
        )
        contract_addresses.append(address)

    nonces: Dict[Address, int] = dict.fromkeys(sender_addresses, 0)
    targets = contract_addresses + sender_addresses

    transactions: List[FuzzerTransactionInput] = []
    for _ in range(num_transactions):
        sender = rng.choice(sender_addresses)
        to = rng.choice(targets)
        gas = rng.choice([100_000, 500_000, 2_000_000])
        transactions.append(
            FuzzerTransactionInput(
                **{"from": sender},
                to=to,
                gas=HexNumber(gas),
                gas_price=HexNumber(10),
                nonce=HexNumber(nonces[sender]),
                value=HexNumber(rng.randrange(0, 10**16)),
                data=Bytes(rng.randbytes(rng.randint(0, 64))),
            )
        )
        nonces[sender] += 1

    env = Environment(
        fee_recipient=Address(0xC0FFEE),
        gas_limit=30_000_000,
        number=1,
        timestamp=1000,
        prev_randao=Hash(seed),
        base_fee_per_gas=7,
    )

    return FuzzerOutput(
        version="2.0",
        fork=fork,
        chain_id=HexNumber(1),
        accounts=accounts,
        transactions=transactions,
        env=env,
    )
