"""
Seeded, reproducible generator of ``FuzzerOutput`` cases.

Every case is fully determined by ``(fork, GENERATOR_VERSION, seed)``, so a
seed alone reproduces a case exactly. Bump ``GENERATOR_VERSION`` whenever the
generation logic changes, so old seeds are never silently reinterpreted.

The bytecode generator is *stack-aware*: it tracks a virtual stack height and
only emits an opcode once enough items are present (pushing operands first
when needed). This keeps generated programs executing real logic instead of
reverting immediately on a stack underflow, which is what makes the corpus
worth running.
"""

import random
from typing import Dict, List, Optional

from execution_testing.base_types import (
    Address,
    Bytes,
    Hash,
    HexNumber,
)
from execution_testing.eip_properties import fuzz_precompile_targets
from execution_testing.forks import Fork
from execution_testing.fuzzing import (
    ValueDomains,
    fork_domains,
    fuzzed_bytecode,
    fuzzed_calldata,
    mixed_address_pool,
)
from execution_testing.test_types import Environment
from execution_testing.test_types.account_types import EOA
from execution_testing.vm import Opcodes as Op

from .models import (
    FuzzerAccountInput,
    FuzzerOutput,
    FuzzerTransactionInput,
)

# Contract bodies and calldata come from the shared strategy library
# (`execution_testing.fuzzing`), the same helpers test authors use. Bump
# this whenever generation logic changes so old seeds are not silently
# reinterpreted.
GENERATOR_VERSION = 12

DESTRUCTOR_ADDRESS = 0x1FFFF
"""Helper contract whose code is `ORIGIN SELFDESTRUCT`."""

SPILLER_ADDRESS = 0x1FFFE
"""Helper contract that charges state gas and then halts exceptionally.

It writes a fresh storage slot -- keyed on `GAS`, so repeat calls in one
block keep paying the full set cost rather than rewriting one slot -- and
then runs onto an undefined byte. A frame that charges state gas it could
afford has spilled (the reservoir is empty for any transaction under the
execution-gas cap), and halting exceptionally is the only path that
forfeits the frame's gas: together they are the precondition for the
halt-chain settlement rule of EIP-8037.
"""

BLOCK_GAS_LIMIT = 30_000_000

RESERVOIR_TX_RATE = 0.35
"""Fraction of transactions drawn above the execution-gas cap, so the
transaction carries a non-empty state gas reservoir.

`validate_transaction` caps the intrinsic cost against
`TX_MAX_GAS_LIMIT`, never `tx.gas`, so gas above the cap is valid and
becomes the reservoir (EIP-8037). Drawing only at or below the cap left
the reservoir empty in every case, which made every state charge spill
and left the branch that serves a charge *from* the reservoir dark.
"""

DISCARDED_DRAWS: Dict[str, int] = {}
"""Per-domain count of drawn values the gas budget could not accept.

A domain value that never fits is dead weight in the mixture, and
dropping it quietly reads downstream as a mysteriously low event rate
rather than as a narrowed domain. Counting it makes the narrowing a
number. Reset by `reset_discarded_draws` before a measured run.
"""


def reset_discarded_draws() -> None:
    """Clear the discarded-draw counters before a measured run."""
    DISCARDED_DRAWS.clear()


PRECOMPILE_FUNDING_RATE = 0.25
"""Fraction of cases that seed the precompiles into the pre-state. The
majority leave them absent, so a value-bearing call to one pays the
account-creation charge -- the historically bug-productive path."""


def _derive_key(rng: random.Random) -> Hash:
    """Draw a valid secp256k1 private key deterministically."""
    # secp256k1 order; any value in [1, n-1] is a valid key.
    n = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
    return Hash((rng.randrange(1, n)).to_bytes(32, "big"))


def generate_fuzzer_output(
    fork: Fork,
    seed: int,
    *,
    num_senders: int = 3,
    num_contracts: int = 3,
    num_transactions: int = 5,
    max_ops_per_contract: int = 40,
    domains: Optional[ValueDomains] = None,
) -> FuzzerOutput:
    """
    Generate one reproducible ``FuzzerOutput`` for the given fork and seed.

    Senders are funded EOAs with deterministic keys; contracts hold
    stack-aware generated bytecode. Transactions reference senders and
    target contracts (or perform value transfers) with correct per-sender
    nonces.

    ``domains`` overrides the value distributions and walk-action weights
    (the experiment arms inject one here); ``None`` uses the fork default,
    so passing it is distribution-neutral -- the default reproduces the
    generator byte-for-byte.
    """
    # Seed from a stable string; a raw tuple hash would be salted per process.
    rng = random.Random(f"{GENERATOR_VERSION}:{fork.name()}:{seed}")

    accounts: Dict[Address, FuzzerAccountInput] = {}

    sender_addresses: List[Address] = []
    for _ in range(num_senders):
        key = _derive_key(rng)
        address = Address(EOA(key=key))
        accounts[address] = FuzzerAccountInput(
            balance=HexNumber(10**20),
            nonce=HexNumber(0),
            private_key=key,
        )
        sender_addresses.append(address)

    # Manifest-driven: precompiles the fork introduced are up-weighted, so
    # the fuzzer aims at the changed surface (see eip_properties.targeting).
    precompiles = fuzz_precompile_targets(fork)
    if domains is None:
        domains = fork_domains(fork, BLOCK_GAS_LIMIT)

    # One mixed pool: contracts call every sibling (nested frames and
    # recursion arise naturally) but also senders, the precompile-range
    # boundary, and addresses that do not exist yet -- and transactions
    # can enter at any of them, precompiles included.
    contract_ints = [0x10000 + i for i in range(num_contracts)]
    pool = mixed_address_pool(
        precompiles,
        code=contract_ints,
        senders=[int.from_bytes(bytes(a), "big") for a in sender_addresses],
    )
    # A funded precompile is an edge every client must handle -- but an
    # UNFUNDED one is the richer path: sending value to a precompile that
    # does not exist yet pays the account-creation charge, and that is
    # where clients have actually diverged. Funding them in every case
    # silently deleted that precondition, so it is now a minority draw and
    # most cases keep the precompiles absent from the pre-state.
    if rng.random() < PRECOMPILE_FUNDING_RATE:
        for one_wei in pool.one_wei_accounts():
            accounts[Address(one_wei)] = FuzzerAccountInput(
                balance=HexNumber(1),
            )
    accounts[Address(DESTRUCTOR_ADDRESS)] = FuzzerAccountInput(
        balance=HexNumber(0),
        nonce=HexNumber(1),
        code=Bytes(bytes(Op.ORIGIN + Op.SELFDESTRUCT)),
    )
    accounts[Address(SPILLER_ADDRESS)] = FuzzerAccountInput(
        balance=HexNumber(0),
        nonce=HexNumber(1),
        code=Bytes(bytes(Op.PUSH1(1) + Op.GAS + Op.SSTORE + Op.INVALID)),
    )
    contract_addresses: List[Address] = []
    for target in contract_ints:
        address = Address(target)
        accounts[address] = FuzzerAccountInput(
            balance=HexNumber(rng.randrange(0, 10**18)),
            nonce=HexNumber(0),
            code=Bytes(
                bytes(
                    fuzzed_bytecode(
                        rng,
                        max_ops=max_ops_per_contract,
                        precompiles=precompiles,
                        call_targets=pool.call_targets(),
                        selfdestructor=DESTRUCTOR_ADDRESS,
                        spiller=SPILLER_ADDRESS,
                        domains=domains,
                    )
                )
            ),
            storage={
                HexNumber(key): HexNumber(value)
                for key, value in domains.storage_seed(rng).items()
            },
        )
        contract_addresses.append(address)

    nonces: Dict[Address, int] = dict.fromkeys(sender_addresses, 0)
    tx_targets = pool.tx_targets()

    transactions: List[FuzzerTransactionInput] = []
    # Transactions must fit the block, or the block itself is invalid.
    gas_budget = BLOCK_GAS_LIMIT
    tx_gas_cap = fork.transaction_gas_limit_cap() or BLOCK_GAS_LIMIT
    tx_gas_choices = tuple(
        tx_gas_cap // divisor for divisor in (128, 32, 8, 1)
    )
    for _ in range(num_transactions):
        sender = rng.choice(sender_addresses)
        to = Address(rng.choice(tx_targets))
        choices = tx_gas_choices
        if domains.reservoir_tx_gas and rng.random() < RESERVOIR_TX_RATE:
            choices = domains.reservoir_tx_gas + tx_gas_choices
        affordable = [g for g in choices if g <= gas_budget]
        for rejected in choices:
            if rejected > gas_budget:
                DISCARDED_DRAWS["tx_gas"] = (
                    DISCARDED_DRAWS.get("tx_gas", 0) + 1
                )
        if not affordable:
            break
        gas = rng.choice(affordable)
        gas_budget -= gas
        transactions.append(
            FuzzerTransactionInput(
                **{"from": sender},
                to=to,
                gas=HexNumber(gas),
                gas_price=HexNumber(10),
                nonce=HexNumber(nonces[sender]),
                value=HexNumber(rng.randrange(0, 10**16)),
                data=Bytes(fuzzed_calldata(rng, domains=domains)),
            )
        )
        nonces[sender] += 1

    env = Environment(
        fee_recipient=Address(0xC0FFEE),
        gas_limit=BLOCK_GAS_LIMIT,
        number=1,
        timestamp=1000,
        prev_randao=Hash(seed),
        base_fee_per_gas=7,
    )

    return FuzzerOutput(
        version="2.0",
        fork=fork,
        chain_id=HexNumber(1),
        accounts=accounts,
        transactions=transactions,
        env=env,
    )
